In [3]:
# %pip install numpy
import numpy as np

In [11]:
x = np.array([1, 2, 3])
x.ndim

1

In [12]:
type(x)

numpy.ndarray

In [13]:
y = np.array([[1, 2, 3], [4, 5, 6]])
y.ndim

2

In [25]:
z = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
z.ndim

3

In [29]:
z[1, 0, 1]

np.int64(2)

In [31]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
np.ones((3, 3), dtype='float32')

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [35]:
np.full((3, 3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [36]:
np.random.random((3, 3))

array([[0.59599816, 0.78666027, 0.57428743],
       [0.21661561, 0.18788666, 0.7393004 ],
       [0.3668176 , 0.7082403 , 0.65767563]])

In [38]:
np.random.randint(0, 10, (3, 3))

array([[1, 5, 5],
       [8, 4, 9],
       [3, 4, 7]])